identifiedBy:string
familly_ref:string
familly:string
genus_ref:integer
species_ref:integer
genus:string
species:string
record_date_note:string
author:string
scan_num:string
subspecies:string
specimen_count:integer
material_organ:string
material_integrity:integer
material_state:integer
province_code:string
province:string
municipality:string
locality:string
sampling_location:string
habitat:string
remarks_1:string
remarks_2:string
taxon:string